plugins {
    id 'net.fabricmc.fabric-loom' version '1.16.3'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()

    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }

    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/releases/"
    }

    maven {
        name = "Architectury"
        url = "https://maven.architectury.dev/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
    implementation "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}"

    implementation include("javazoom:jlayer:1.0.1")
}

processResources {
    inputs.property "version", project.version
    inputs.property "mod_id", project.mod_id
    inputs.property "mod_name", project.mod_name

    filesMatching("fabric.mod.json") {
        expand(
                "version": project.version,
                "mod_id": project.mod_id,
                "mod_name": project.mod_name
        )
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }

    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

jar {
    archiveClassifier = ""
}

sourcesJar {
    archiveClassifier = "sources"
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {
    }
}
