pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }

        gradlePluginPortal()
        mavenCentral()
    }

    resolutionStrategy {
        eachPlugin {
            if (
                    requested.id.id == "fabric-loom" ||
                    requested.id.id == "net.fabricmc.fabric-loom" ||
                    requested.id.id == "net.fabricmc.fabric-loom-remap"
            ) {
                useModule("net.fabricmc:fabric-loom:${requested.version}")
            }
        }
    }
}

rootProject.name = "Custom-Chat-Tabs"
